name: Create Pull Request from Jira

on:
  repository_dispatch:
    types: [create-pr]

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar payload recebido
        run: |
          echo "Payload completo:"
          echo '${{ toJson(github.event) }}'

      - name: Validar branch enviada
        run: |
          if [ -z "${{ github.event.client_payload.branch_name }}" ]; then
            echo "❌ O Jira não enviou branch_name"
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.client_payload.branch_name;
            const key = context.payload.client_payload.issue_key;
            const summary = context.payload.client_payload.issue_summary;

            const title = `[${key}] - ${summary}`;
            const body = "PR criado automaticamente pelo Jira.";

            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: "main",
              title,
              body
            });

            core.info(`PR criado: ${pr.data.html_url}`);
