name: Create PR from Jira

on:
  repository_dispatch:
    types: [create-pr]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Criar Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const branchName = context.payload.client_payload.branch_name;
            const baseBranch = context.payload.client_payload.base || "develop";
            const title = context.payload.client_payload.title || `PR autom√°tico para ${branchName}`;
            const body = context.payload.client_payload.body || "Pull Request criado automaticamente pelo Jira.";

            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branchName,
              base: baseBranch,
              title,
              body,
            });

            console.log("PR criado:", pr.html_url);
